#resilience4j:
#  ratelimiter:
#    configs:
#      default:
#        timeoutDuration: 5 # 线程等待权限的默认等待时间
#        limitRefreshPeriod: 2s # 限流器每隔1s刷新⼀次，将允许处理的最⼤请求重置为2
#        limitForPeriod: 1 #在⼀个刷新周期内，允许执⾏的最⼤请求数
#  instances:
#    backendA:
#      baseConfig: default
#    backendB:
#      timeoutDuration: 5
#      limitRefreshPeriod: 1s
#      limitForPeriod: 5
